export const WHATSAPP_NUMBER = "15551234567";

const image = (label, color = "d7e5df") =>
  `https://placehold.co/700x520/${color}/17322c?text=${encodeURIComponent(label)}`;

export const categories = [
  "Floor Cleaner",
  "Toilet Cleaner",
  "Glass Cleaner",
  "Disinfectant",
  "Degreaser",
  "Surface Cleaner",
  "Laundry",
  "Kitchen",
  "Hygiene",
  "Cleaning Tools",
  "Garbage Bags",
  "Industrial Chemicals",
];
export const applications = [
  "Factory",
  "Office",
  "Hotel",
  "Hospital",
  "Restaurant",
  "School",
  "Warehouse",
];
export const packSizes = ["1L", "5L", "20L", "50L", "Bulk"];
export const industries = [
  "Factory",
  "Office",
  "Hotel",
  "Hospital",
  "Restaurant",
  "School",
  "Warehouse",
  "Commercial Building",
  "Facility Management",
];

const productSeed = [
  [
    "heavy-duty-floor-cleaner",
    "Heavy Duty Floor Cleaner",
    "Floor Cleaner",
    "Factory, Warehouse",
    "Cuts through oil, grease, and tracked-in dirt on hard industrial floors.",
    ["1L", "5L", "20L"],
    "high",
    "b7d8cc",
  ],
  [
    "industrial-floor-cleaner",
    "Industrial Floor Cleaner",
    "Floor Cleaner",
    "Factory, Warehouse",
    "Low-foam concentrate for machine and manual floor cleaning.",
    ["5L", "20L", "50L"],
    "high",
    "c6ded4",
  ],
  [
    "multipurpose-surface-cleaner",
    "Multipurpose Surface Cleaner",
    "Surface Cleaner",
    "Office, Hotel, School",
    "Everyday cleaner for desks, counters, doors, and washable surfaces.",
    ["1L", "5L", "20L"],
    "high",
    "dbe7df",
  ],
  [
    "glass-window-cleaner",
    "Glass & Window Cleaner",
    "Glass Cleaner",
    "Office, Hotel, Commercial Building",
    "Streak-free clarity for glass, mirrors, and polished surfaces.",
    ["1L", "5L"],
    "medium",
    "b9d7d2",
  ],
  [
    "toilet-bowl-cleaner",
    "Toilet Bowl Cleaner",
    "Toilet Cleaner",
    "Hotel, Hospital, School",
    "Viscous acidic formula for hygienic toilet and urinal care.",
    ["1L", "5L", "20L"],
    "high",
    "c9ddd2",
  ],
  [
    "heavy-duty-degreaser",
    "Heavy Duty Degreaser",
    "Degreaser",
    "Factory, Restaurant, Warehouse",
    "Powerful alkaline degreaser for machinery, kitchens, and workshop floors.",
    ["5L", "20L", "50L"],
    "high",
    "e4d4bd",
  ],
  [
    "industrial-disinfectant",
    "Industrial Disinfectant",
    "Disinfectant",
    "Hospital, Factory, School",
    "Broad-spectrum disinfectant for high-touch and hard non-porous surfaces.",
    ["1L", "5L", "20L"],
    "high",
    "c2d9dc",
  ],
  [
    "bathroom-cleaner",
    "Professional Bathroom Cleaner",
    "Toilet Cleaner",
    "Hotel, Hospital, Office",
    "Removes soap scum, mineral deposits, and daily bathroom soils.",
    ["1L", "5L", "20L"],
    "medium",
    "d2dfca",
  ],
  [
    "kitchen-cleaner",
    "Commercial Kitchen Cleaner",
    "Kitchen",
    "Restaurant, Hotel, Hospital",
    "Food-service safe cleaner for preparation areas and equipment exteriors.",
    ["1L", "5L", "20L"],
    "high",
    "e2d7bf",
  ],
  [
    "liquid-hand-wash",
    "Liquid Hand Wash",
    "Hygiene",
    "Office, Hospital, School",
    "Gentle, high-frequency hand wash for professional washrooms.",
    ["1L", "5L", "20L"],
    "high",
    "d1e2d9",
  ],
  [
    "hand-sanitizer",
    "Alcohol Hand Sanitizer",
    "Hygiene",
    "Hospital, Office, Restaurant",
    "Fast-drying 70% alcohol sanitizer for stations and wall dispensers.",
    ["1L", "5L", "20L"],
    "high",
    "c8dbe2",
  ],
  [
    "laundry-detergent",
    "Commercial Laundry Detergent",
    "Laundry",
    "Hotel, Hospital, School",
    "Concentrated detergent engineered for institutional laundry systems.",
    ["5L", "20L", "50L"],
    "high",
    "d8d5ca",
  ],
  [
    "dishwashing-liquid",
    "Industrial Dishwashing Liquid",
    "Kitchen",
    "Restaurant, Hotel, Hospital",
    "High-performance manual dishwashing formula with quick rinse.",
    ["1L", "5L", "20L"],
    "high",
    "d8e0c2",
  ],
  [
    "air-freshener",
    "Professional Air Freshener",
    "Surface Cleaner",
    "Hotel, Office, Commercial Building",
    "Long-lasting fragrance system for guest and public areas.",
    ["1L", "5L"],
    "medium",
    "ddd2c7",
  ],
  [
    "garbage-bags",
    "Heavy Duty Garbage Bags",
    "Garbage Bags",
    "Factory, Restaurant, Warehouse",
    "Tear-resistant bags for commercial waste collection and transfer.",
    ["1L", "Bulk"],
    "high",
    "c7d2cc",
  ],
  [
    "microfiber-cloth",
    "Microfiber Cleaning Cloth",
    "Cleaning Tools",
    "Office, Hotel, Hospital",
    "Low-lint microfiber cloths for efficient professional cleaning.",
    ["Bulk"],
    "medium",
    "d2ddd5",
  ],
  [
    "floor-wiper",
    "Commercial Floor Wiper",
    "Cleaning Tools",
    "Factory, Office, School",
    "Durable floor wiper with replaceable head for daily maintenance.",
    ["Bulk"],
    "medium",
    "d8d3c9",
  ],
  [
    "industrial-cleaning-brush",
    "Industrial Cleaning Brush",
    "Cleaning Tools",
    "Factory, Warehouse, Restaurant",
    "Stiff-bristle brush for equipment, drains, and hard-to-reach areas.",
    ["Bulk"],
    "medium",
    "d7d1c2",
  ],
  [
    "scrub-pads",
    "Machine Scrub Pads",
    "Cleaning Tools",
    "Factory, Commercial Building",
    "Color-coded pads for scrubber dryers and rotary machines.",
    ["Bulk"],
    "medium",
    "c8d4d8",
  ],
  [
    "commercial-toilet-cleaner",
    "Commercial Toilet Cleaner",
    "Toilet Cleaner",
    "Hotel, Hospital, Office",
    "Daily toilet care formula designed for frequent professional use.",
    ["1L", "5L", "20L"],
    "high",
    "c5dbd1",
  ],
];

export const products = productSeed.map(
  (
    [slug, name, category, application, description, sizes, popularity, color],
    index,
  ) => ({
    id: index + 1,
    slug,
    name,
    category,
    application,
    applications: application.split(", "),
    description,
    sizes,
    popularity,
    color,
    image: image(name, color),
    status: "Active",
    createdAt: `2025-0${(index % 9) + 1}-15`,
    features: [
      "Professional concentrate",
      "Consistent batch quality",
      "Bulk reorder support",
    ],
    specifications: [
      "For commercial use",
      "Store in a cool, dry area",
      "Follow label directions",
    ],
    related: [((index + 1) % 20) + 1, ((index + 2) % 20) + 1],
    usage:
      "Dilute according to soil level and application. Test on an inconspicuous area before first use.",
    safety:
      "Wear suitable gloves and avoid contact with eyes. Keep away from children and food preparation areas.",
  }),
);

export const solutions = industries.map((name, index) => ({
  slug: name.toLowerCase().replaceAll(" ", "-"),
  name,
  title: `Cleaning Solutions for ${
    {
      Factory: "Factories",
      Office: "Offices",
      Hotel: "Hotels",
      Hospital: "Hospitals",
      Restaurant: "Restaurants",
      School: "Schools",
      Warehouse: "Warehouses",
      "Commercial Building": "Commercial Buildings",
      "Facility Management": "Facility Management",
    }[name]
  }`,
  description: `Reliable cleaning products and supply planning for ${name.toLowerCase()} teams that need consistent standards and dependable delivery.`,
  requirements: [
    "Floor cleaning",
    "Surface disinfection",
    "Washroom cleaning",
    "Waste management",
    "Routine maintenance",
  ],
  recommended: products
    .filter((product) =>
      product.applications.some((item) =>
        item.toLowerCase().includes(name.toLowerCase().split(" ")[0]),
      ),
    )
    .slice(0, 4),
  index,
}));

export const faqs = [
  [
    "Do you supply products in bulk?",
    "Yes. We supply single cases through recurring pallet and bulk programs, with pricing tailored to volume and delivery cadence.",
  ],
  [
    "Can I request custom pricing?",
    "Absolutely. Share your product mix and estimated quantities through the quote form and our sales team will prepare a business quote.",
  ],
  [
    "What areas do you deliver to?",
    "We coordinate commercial delivery across major cities and can discuss scheduled delivery for multi-site operations.",
  ],
  [
    "Do you provide products for factories?",
    "Yes. Our range covers factory floors, machinery, washrooms, waste handling, and staff hygiene.",
  ],
  [
    "Can I request a product sample?",
    "Sample availability depends on the product. Mention it in your requirements and the team will confirm options.",
  ],
];
